name: mobile
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.1
  carousel_slider: ^5.0.0
  intl: ^0.20.0
  http: ^1.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo-hanachik.png
    - assets/img/fried_chicken.jpg
    - assets/img/payment/dana.png
    - assets/img/payment/ovo.png
    - assets/img/payment/shopee.png
    - assets/img/payment/qris.png
    - assets/img/makanan/ayam_geprek.png
    - assets/img/makanan/ayam_penyet.jpg
    - assets/img/makanan/nasi_goreng.jpg
    - assets/img/makanan/telur_geprek.jpg
    - assets/img/minuman/kopi.jpg
    - assets/img/minuman/esteh.jpg
    - assets/img/minuman/esjeruk.jpg
    - assets/img/minuman/matcha.jpg
    - assets/img/camilan/terong.jpg
    - assets/img/camilan/jamur.jpg
    - assets/img/camilan/onion.jpg
    - assets/img/camilan/kentang.jpg
